In [4]:
import numpy as np 
list1 = [[1,2,3], [4,5,6], [7,8,9]]
a = np.array(list1)
print(a)
b= a[0:2, 0:2]
print(b)
c= a[1:, 1:]
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [5]:
arr= np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(arr.shape)

(2, 2, 3)


In [10]:
a = np.array([[1,2,3], [4,5,6]]) 
one_a = a.flatten()

print(a)
print(one_a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [18]:
a = np.arange(8) 
a.reshape(4,2)
print(re_a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


6번문제

In [30]:
import pandas as pd 

df = pd.DataFrame( 
    {"이름" :['허준호', '이가원', '배규민', '고고림', '이새봄', '이보람', '이루리', '오다현'], 
     "성별" :['남자', '여자', '남자', '남자', '여자', '여자', '여자', '여자'], 
     "나이" : [30, 24, 23, 21, 28, 26, 24, 24], 
     "키" : [ 183, 162, 179, 182, 160, 163, 157, 172] })
df

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [27]:
condition_df = df[(df['나이'] >= 25) & (df['성별'] == '여자')]
condition_df

이름  성별  나이    키
4  이새봄  여자  28  160
5  이보람  여자  26  163

In [31]:
df.describe()

나이           키
count   8.000000    8.000000
mean   25.000000  169.750000
std     2.878492   10.552589
min    21.000000  157.000000
25%    23.750000  161.500000
50%    24.000000  167.500000
75%    26.500000  179.750000
max    30.000000  183.000000

In [34]:
df.describe()

나이           키
count   8.000000    8.000000
mean   25.000000  169.750000
std     2.878492   10.552589
min    21.000000  157.000000
25%    23.750000  161.500000
50%    24.000000  167.500000
75%    26.500000  179.750000
max    30.000000  183.000000

In [35]:
list1 = list([['허준호','남자','30','183'],
['이가원','여자','24','162'],
['배규민','남자','23','179'],
['고고림','남자','21','182'],
['이새봄','여자','28','160'],
['이보람','여자','26','163'],
['이루리','여자','24','157'],
['오다현','여자','24','172']])
col_names = ['이름','성별','나이','키']
df = pd.DataFrame(list1, columns=col_names)
df
# 자세히보면, 모든값이 앞과 다르게 문자열(object) 형태로 되어있음을 알수있다.

이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [36]:
df.describe()

이름  성별  나이    키
count     8   8   8    8
unique    8   2   6    8
top     허준호  여자  24  183
freq      1   5   3    1

In [37]:
df.set_index('이름', inplace = True)
#이름 컬럼을 행 인덱스로 설정
df

성별  나이    키
이름              
허준호  남자  30  183
이가원  여자  24  162
배규민  남자  23  179
고고림  남자  21  182
이새봄  여자  28  160
이보람  여자  26  163
이루리  여자  24  157
오다현  여자  24  172

9번문제

In [39]:
list1 = [[1,2], [3,4]]
arr = np.array(list1)
bool_index = (arr%2 ==0)
print(bool_index)
print('짝수\n', arr[bool_index])
res = arr[~bool_index]
print('홀수\n', res)

[[False  True]
 [False  True]]
짝수
 [2 4]
홀수
 [1 3]


10번문제

In [43]:
# 2행 4열 넘파이 배열 

arr1 = np.array([[1,2,3,4], [5,6,7,8]])

#배열 복사하기 
arr2 = arr1 
print('arr1', '\n', arr1)
print('arr2', '\n', arr2)
arr1[0,0] = 10 
print('='*20) # 줄 선을 그냥 표시
print('변경 후 -> arr1', '\n', arr1)
print('변경 후 -> arr2', '\n', arr2) 


arr1 
 [[1 2 3 4]
 [5 6 7 8]]
arr2 
 [[1 2 3 4]
 [5 6 7 8]]
변경 후 -> arr1 
 [[10  2  3  4]
 [ 5  6  7  8]]
변경 후 -> arr2 
 [[10  2  3  4]
 [ 5  6  7  8]]


위의 결과를 보니 둘다 같이 변한다.  
arr2 = arr1은 arr2를 복제한것이 아니라, arr2라는 변수에 arr1라는  
변수를 담은 것이다.   
따라서 arr1이 바뀌면, arr2도 역시 바뀌게 된다.   
이를 수정하기 위해선  

In [44]:
# 2행 4열 넘파이 배열 

arr1 = np.array([[1,2,3,4], [5,6,7,8]])

#배열 복사하기 
arr2 = np.array([[1,2,3,4], [5,6,7,8]])
print('arr1', '\n', arr1)
print('arr2', '\n', arr2)
arr1[0,0] = 10 
print('='*20) # 줄 선을 그냥 표시
print('변경 후 -> arr1', '\n', arr1)
print('변경 후 -> arr2', '\n', arr2) 


arr1 
 [[1 2 3 4]
 [5 6 7 8]]
arr2 
 [[1 2 3 4]
 [5 6 7 8]]
변경 후 -> arr1 
 [[10  2  3  4]
 [ 5  6  7  8]]
변경 후 -> arr2 
 [[1 2 3 4]
 [5 6 7 8]]


In [45]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])

#배열 복사하기 
arr2 = arr1.copy() 
print('arr1', '\n', arr1)
print('arr2', '\n', arr2)
arr1[0,0] = 10 
print('='*20) # 줄 선을 그냥 표시
print('변경 후 -> arr1', '\n', arr1)
print('변경 후 -> arr2', '\n', arr2) 

arr1 
 [[1 2 3 4]
 [5 6 7 8]]
arr2 
 [[1 2 3 4]
 [5 6 7 8]]
변경 후 -> arr1 
 [[10  2  3  4]
 [ 5  6  7  8]]
변경 후 -> arr2 
 [[1 2 3 4]
 [5 6 7 8]]
