#### 넘파이는 쉽지만 속도가 느리다 

##### 차원: 관측하고자하는 데이터의 속성
> 튜플?: row (행) 하나를 데이터베이스에서 튜플이라고 한다.  
> 행렬: 2차원 배열. 1차원을 여러개 묶은 배열   
> 텐서: 3차원이상의 배열은 모두 텐서  

##### 배열의 랭크는 차원의 수, 모양은 배열의 차원과 크기를 나타냄
> 2차원배열에서 랭크는 2, 모양은 행이 3개이고 열이 2개이면 (3, 2) 라고 표현함

##### ndarray : 넘파이의 다차원 배열 객체 (중요!)
> 1) 자료형이 모두 같은 데이터를 담은 다차원 배열
> 2) 정수 또는 실수를 저장
> 3) 배열 데이터에도 순서가 있으므로 인덱싱과 슬라이싱이 가능

##### 판다스의 시리즈와 데이터프레임
> 판다스: 파이썬 라이브러리이다. 데이터프레임 자료구조를 제공한다.  
> 시리즈(Series): 인덱스와 값이 한 쌍을 이루는 1차원 자료구조 객체이다.  

넘파이와 판다스 비교 
넘파이의 특징
> 다차원 배열 객체  
> 정교한 브로드캐스팅  
> C , C++ 포트란 코드를 통합  
> 수학적 알고리즘 제공

판다스의 특징  
> 대용량 데이터 처리  
> 시각적으로 알아보기 편리한 표 형태   
> 데이터 분석 도구 제공  

##### 02. 넘파이 활용

1. 넘파이의 배열 생성  
   ndarray를 만들 때 넘파이 라이브러리에 정의된 array() 함수를 사용 

In [2]:
import numpy as np 

# 리스트를 생성하고 배열로 변환
list1 = [1, 2, 3, 4]
a = np.array(list1)
print('a.shape: ', a.shape)
print('a[0]:', a[0]) 
# 왜 a[0] =1 일까? , 2차원과 달리 1차원배열인 경우 df[0]은 열의 인덱스가 0인원소를 가져오라는 말인가?

a.shape:  (4,)
a[0]: 1


In [4]:
# 2차원 배열 생성하기 
b = np.array([[1,2,3], [4,5,6]])
print('b.shape:', b.shape)
print('b[0,0] : ', b[0,0])
print('b[0]:', b[0])

b.shape: (2, 3)
b[0,0] :  1
b[0]: [1 2 3]


In [6]:
a = np.zeros(2) # 0으로 채운 1차원 배열을 생성
print('a\n', a)
b = np.zeros((2,2)) # 0으로 채운 2차원 배열을 생성
print('b\n', b)
c= np.ones((2,3))
print('c\n', c)
d = np.full((2,3), 5) # 지정된 모양에 지정한 값으로 채운 배열을 생성
print('d\n' , d)
e = np.eye(3)
print('e\n', e)

a
 [0. 0.]
b
 [[0. 0.]
 [0. 0.]]
c
 [[1. 1. 1.]
 [1. 1. 1.]]
d
 [[5 5 5]
 [5 5 5]]
e
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 넘파이 배열의 속성

In [3]:
arr = np.array([[1,2,3], [4,5,6]])

print( type(arr))
print( arr.ndim )
print(arr.dtype)
print(arr.itemsize)
print(arr.size)
print(arr.nbytes)
print(arr.T)
print(arr.shape)

# 이거 시험에 물어볼수 있다. 예를들어 arr.shape주고 무엇인가? ( ?, ?)


<class 'numpy.ndarray'>
2
int32
4
6
24
[[1 4]
 [2 5]
 [3 6]]
(2, 3)


In [ ]:
#1차원 배열 생성하기
a = np.arange(8)
print('a\n', a)
#다차원 배열로 변경하기
a.shape = (2,4)
print('shape\n', a)
#1차원 배열로 변경하기
print('flatten\n', a.flatten( ))
#resize 함수로 모양 변경하기
a.resize((4,2))
print('resize\n', a)

In [ ]:
# T는 행렬의 행과 열을 교차

a = np.array([[0, 1, 2], [3, 4, 5]])
print('a\n', a)
b = a.transpose( )
print('b\n', b)
c = a.T
print('c\n', c)


### 10월 16일 

In [2]:
mask = np.array([0, 1, 1, 0], dtype=bool)
print(mask)

[False  True  True False]


In [3]:
mask = np.array([0, 1, 1, 0], dtype=bool)
#dtype = 데이터 타입은 불리안 타입이다. 
# 불리안타입은 참인가 거짓인가 표현하라는말 
print(mask)
# 0은 항상 false , 1은 True

data = np.random.randn(4,2)
# 행이 4개이며 열이 2개인 데이터프레임 난수를 생성해줘

print('\ndata 출력\n',data) #랜덤 데이터 배열 data는 책과 다르게 나타남



print('\n마스킹된 데이터 출력\n',data[mask]) # True인 요소를 출력해줘
print('\n마스킹 역전된 데이터 출력\n',data[~mask]) # False인 요소를 출력해줘

[False  True  True False]

data 출력
 [[-1.79559877 -0.37282862]
 [ 0.18247197 -0.0255961 ]
 [ 0.52965546  0.20242367]
 [-1.14207307  0.56518628]]

마스킹된 데이터 출력
 [[ 0.18247197 -0.0255961 ]
 [ 0.52965546  0.20242367]]

마스킹 역전된 데이터 출력
 [[-1.79559877 -0.37282862]
 [-1.14207307  0.56518628]]


In [4]:
#조건식 마스킹으로 데이터에서 기준보다 큰 값이나 작은값을 쉽게 찾는다.

posit = data[data > 0] # data의 요소들중에서 요소들이 0보다 큰 요소들만 posit에 저장
print('양수 데이터 출력', '\n',posit)
#다중 조건
over1 = data[1][data[1] > 0] # data[1] : index행번호가 1인 행
# 그중에서 0보다 큰 요소들을 보여줘
print('두 번째 행의 양수 데이터 출력','\n',over1)

양수 데이터 출력 
 [0.18247197 0.52965546 0.20242367 0.56518628]
두 번째 행의 양수 데이터 출력 
 [0.18247197]


In [5]:
data[2][data[2]>0]

array([0.52965546, 0.20242367])

####  유니버설 함수와 브로드캐스팅

배열을 복사할 필요가 있다.   
변수를 copy한다는건 배열의 값들을 copy한다는것인데,  
얕은복사, 깊은복사가 있음  
얕은 복사는 등호로 복제  
깊은 복사 : copy()함수를 사용.  

##### 얕은 복사

In [7]:
a = np.arange(6) #0부터 5까지 6개의 요소를 1차원 배열 생성
b = a
print(a)
print(b is a) #is는 논리연산자, 불리안 타입의 결과를 내뱉는다.
b[0] = 10 #인덱스 번호가 0인 열에 있는 요소(여기선 0임)를 10으로 바꾼다.
print(a) 

[0 1 2 3 4 5]
True
[10  1  2  3  4  5]


In [8]:
a = np.arange(6)
c = a.copy( )
c[0] = 20
print('A: ', a)
print('C: ', c)

A:  [0 1 2 3 4 5]
C:  [20  1  2  3  4  5]


copy 함수를 사용하면 복사본인 배열 c의 값을 수정해도 원본 a에 영향이 없음

#### 배열 정렬

In [10]:
a = np.array([3, 2, 5, 1, 4])
print('원본\n',a)
print('정렬 후\n',np.sort(a))
print('원본\n',a)
print('정렬한 인덱스\n',np.argsort(a))
a.sort( )
print('원본\n',a)

원본
 [3 2 5 1 4]
정렬 후
 [1 2 3 4 5]
원본
 [3 2 5 1 4]
정렬한 인덱스
 [3 1 0 4 2]
원본
 [1 2 3 4 5]


np.sort()와  배열.sort()의 차이?  
np.sort()는 배열을 해도, 원본을 유지하지만,  
배열.sort() 는 배열을 하게된다면, 원본도 정렬이 된다.  

In [13]:
a = np.array([3, 2, 5, 1, 4])
cor_a = np.sort(a)
print(cor_a)
print(a)
# np.sort는 원본을 훼손하지 않는다. 

[1 2 3 4 5]
[3 2 5 1 4]


In [14]:
a= np.array([1,2,3])
b= np.array([4])
c=a+b
print(c)

#시험문제내실때, 단답으로 낼수있을것같지만사지선다로 
#a변수 , b변수일때 c의 변수는 4, 5, 6 이다 ->오답 : 이게 교수님 좋아하는 유형임

[5 6 7]


In [26]:
# 초콜릿
import pandas as pd

In [1]:
import numpy as np

In [2]:
data = np.loadtxt('C:\\sweet\\chocolate_ranking.csv', delimiter=',')
data

array([[1.000e+00, 2.016e+03, 6.300e-01, 3.750e+00],
       [2.000e+00, 2.015e+03, 7.000e-01, 2.750e+00],
       [3.000e+00, 2.015e+03, 7.000e-01, 3.000e+00],
       ...,
       [1.793e+03, 2.011e+03, 6.500e-01, 3.500e+00],
       [1.794e+03, 2.011e+03, 6.200e-01, 3.250e+00],
       [1.795e+03, 2.010e+03, 6.500e-01, 3.000e+00]])

#### pandas

가장 근본적인 차이는 칼럼갯수에 있다.  
시리즈는 칼럼이 1개, 데이터프레임은 1개 이상이다.  
출처: https://tbr74.tistory.com/entry/판다스-Dataframe과-Series의-차이점 [JayD:티스토리]  

In [11]:
a = np.arange(0, 10)
a.shape = (2, 5)
print(a)
a= a.T
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [15]:
import numpy as np
import pandas as pd
# 예시 데이터 생성
data = np.random.randn(4, 2)  # 4행 2열의 랜덤 데이터 생성
print("data:\n", data)

# 마스크 생성
mask = np.array([[1, 0], [1, 0], [1, 0], [1, 0]])  # 4행 2열의 마스크 배열
mask = mask.astype(bool)  # 불리언 타입으로 변환
print("\nmask:\n", mask)

# 마스킹된 데이터
masked_data = data[mask]  # True인 값의 데이터만 선택
print("\n마스킹된 데이터 출력:\n", masked_data)

# 마스킹 역전된 데이터
inverse_masked_data = data[~mask]  # False인 값의 데이터만 선택
print("\n마스킹 역전된 데이터 출력:\n", inverse_masked_data)

data:
 [[-0.69983801  0.18915611]
 [ 0.82796902  0.63809345]
 [-0.36497387 -0.5550336 ]
 [-0.61155063  0.42391897]]

mask:
 [[ True False]
 [ True False]
 [ True False]
 [ True False]]

마스킹된 데이터 출력:
 [-0.69983801  0.82796902 -0.36497387 -0.61155063]

마스킹 역전된 데이터 출력:
 [ 0.18915611  0.63809345 -0.5550336   0.42391897]


In [17]:
dict1 = {'이름':{0:'한빛', 1:'한결', 2:'한라'},
 '성별':{0:'남자', 1:'남자', 2:'여자'},
 '나이':{0:'20', 1:'21', 2:'20'},
 '키':{0:'180', 1:'177', 2:'160'}}
pd.DataFrame(dict1)

이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160